### ISSUE TITLE
The Express example in README.md isn't working

### ISSUE THREAD

**Issue by fontanon** [vesse/passport-ldapauth#23]
The express example described in the README.md file fails with "Bad Request" when doing POST /login

Evidence: http://runnable.com/VOXApb1vNXtApwTG/passport-ldapauth-example-fails-for-node-js-and-hello-world

**Comment by vesse** [comment]
Are you sure your request is correct? Using the code and package.json from the link above and running this:

```bash
curl \
  -X POST \
  -d "{\"username\": \"test\", \"password\": \"test\"}" \
  http://localhost/login
```

will return `Bad Request` because `body-parser` does not know how to parse the request when no `Content-Type` is defined and thus [missing username/password causes `HTTP 400`](https://github.com/vesse/passport-ldapauth/blob/ac6e5757bb0d950fb5f65488f6ebbab5420a1579/lib/passport-ldapauth/strategy.js#L134-L136). 

But when I add correct headers to the request I get `Unauthorized` as expected:

```bash
curl \
  -X POST \
  -H "Content-Type: application/json" \
  -d "{\"username\": \"test\", \"password\": \"test\"}" \
  http://localhost/login
```

**Comment by fontanon** [comment]
You're right it was a matter of a bad request.
