### ISSUE TITLE
Unable to access ldaps - ldapjs error

### ISSUE THREAD

**Issue by random6886** [vesse/passport-ldapauth#26]
I am currently using Node.js version 0.12.2 and passport-ldapauth@0.3.0 with passport @0.2.1.

I'm running into an issue where I am able to talk to an ldap server using "ldap://....:389" successfully, however when using ldaps://, I run into the problem as documented here:

http://stackoverflow.com/questions/28773546/nodejs-passport-ldapauth-cannot-read-on-property-of-undefined

Following the recommended solution of replacing the sub-module for ldapjs seems to fix the problem. 

## node.js project before:

├─┬ passport@0.2.1
│ ├── passport-strategy@1.0.0
│ └── pause@0.0.1
├─┬ passport-ldapauth@0.3.0
│ ├─┬ ldapauth-fork@2.3.1
│ │ ├── bcryptjs@2.1.0
│ │ ├─┬ ldapjs@0.7.1        **<----- Look here**
│ │ │ ├── asn1@0.2.1
│ │ │ ├── assert-plus@0.1.5
│ │ │ ├─┬ bunyan@0.22.1
│ │ │ │ └── mv@0.0.5
│ │ │ ├─┬ nopt@2.1.1
│ │ │ │ └── abbrev@1.0.5
│ │ │ └─┬ pooling@0.4.6
│ │ │   ├── once@1.3.0
│ │ │   └─┬ vasync@1.4.0
│ │ │     ├─┬ jsprim@0.3.0
│ │ │     │ ├── extsprintf@1.0.0
│ │ │     │ ├── json-schema@0.2.2
│ │ │     │ └── verror@1.3.3
│ │ │     └─┬ verror@1.1.0
│ │ │       └── extsprintf@1.0.0 
│ │ └── lru-cache@2.5.0
│ └── passport-strategy@1.0.0

## To fix:

(Start at project root)
cd ./passport-ldapauth/node_modules/ldapauth-fork/node_modules/ldapjs
cd ..
npm rm ldapjs unbuild ldapjs@0.7.1
npm install git://github.com/mcavage/node-ldapjs.git

├─┬ passport@0.2.1
│ ├── passport-strategy@1.0.0
│ └── pause@0.0.1
├─┬ passport-ldapauth@0.3.0
│ ├─┬ ldapauth-fork@2.3.1
│ │ ├── bcryptjs@2.1.0
│ │ ├─┬ ldapjs@0.7.1    **<--- Look here**
│ │ │ ├── asn1@0.2.2
│ │ │ ├── assert-plus@0.1.5 
│ │ │ ├─┬ backoff@2.4.1
│ │ │ │ └── precond@0.2.3
│ │ │ ├─┬ bunyan@1.3.3
│ │ │ │ ├─┬ mv@2.0.3
│ │ │ │ │ ├─┬ mkdirp@0.5.0
│ │ │ │ │ │ └── minimist@0.0.8
│ │ │ │ │ ├── ncp@0.6.0
│ │ │ │ │ └── rimraf@2.2.8
│ │ │ │ └── safe-json-stringify@1.0.3
│ │ │ ├── dashdash@1.7.3
│ │ │ ├─┬ dtrace-provider@0.4.0
│ │ │ │ └── nan@1.5.3
│ │ │ ├── ldap-filter@0.2.1
│ │ │ ├─┬ once@1.3.1
│ │ │ │ └── wrappy@1.0.1
│ │ │ ├─┬ vasync@1.6.2
│ │ │ │ └─┬ verror@1.1.0
│ │ │ │   └── extsprintf@1.0.0
│ │ │ └─┬ verror@1.6.0
│ │ │   └── extsprintf@1.2.0
│ │ └── lru-cache@2.5.0
│ └── passport-strategy@1.0.0

The process of having to manually update the project makes node.js very difficult to manually deploy. I'm not too sure if this should be fixed at the ldapauth-fork or not?

**Comment by random6886** [comment]
I should also note that I am using the npm install passport-ldapauth, so I am using the current version. I noticed in your ldapauth-fork that you had tried to correct this issue.

**Comment by vesse** [comment]
This issue comes from mcavage/node-ldapjs#256, encrypted connections work fine with Node.js v0.10 (I told this to mr. Carpani in response to his email but he did not include the reason to the reply in the question above).  

I'm going to see if new version of `ldapjs` will be released soonish, I prefer not to depend on unreleased versions (one reason being that I know the library is used in environments that have restricted Internet access and installing from GitHub would not work).

**Comment by random6886** [comment]
Ah I see. I appreciate such a quick reply back! I suppose I just got really confused when the version was first: ldapjs@0.7.1 and then after I apply that pull, it's still that same version. Furthermore, several of the sub-modules have pretty old versions it appears ex: bunyan@0.22.1 -> bunyan@1.3.3.

Appreciate the quick response!

**Comment by vesse** [comment]
Yeah, the versions come from [ldapjs package.json](https://github.com/mcavage/node-ldapjs/blob/master/package.json) even when you install from GitHub, so it might seem confusing. In reality there has been [quite a lot of changes since the release of ldapjs@0.7.1](https://github.com/mcavage/node-ldapjs/compare/0a8810996d9befad8620e197fbc0d50cd98938ce...773a1c6fd20ca50174a5a82ec61b84361f51f81c), including eg. bunyan dependency upgrade.

But good news is that you should be able to work around this. If you add `ldapjs` (from GitHub) to the `package.json` of your project, `ldapauth-fork` and therefore `passport-ldapauth` should use that one instead.

**Comment by csulok** [comment]
Thanks for the suggestion on adding mcavage/node-ldapjs as a dep. You might want to consider doing that in passport-ldapauth's package.json too, since the author of node-ldapjs doesn't seem too eager to fix things there (looking at the last comments being 17 days old, the patch more than a month now).

**Comment by ricardohbin** [comment]
As I told in https://github.com/mcavage/node-ldapjs/issues/258, we can bypass the **dtracer** exceptions, since it is an optional module.

`npm install passport-ldapauth --no-optional`

**Comment by axkibe** [comment]
Thank you a lot for the workaround! With this is works...

**Comment by mayur-arora** [comment]
Any chance of a newer version ( with this fix) being released soon...can't depend on an unreleased version.

**Comment by vesse** [comment]
@mayur-arora well there has not been a new release of `ldapjs` so me adding this unreleased dependency to this module kinda makes you use an unreleased version as well :) And I too don't want to publish a module that depends on an unreleased version, but if someone wants to work around this issue by using the unreleased version of `ldapjs` it is entirely possible as described above.

**Comment by mayur-arora** [comment]
@vesse Thanks . Just want to confirm. I was actually referring to the fix for https://github.com/mcavage/node-ldapjs/issues/256
