### ISSUE TITLE
Bad Request error using passport-ldapauth

### ISSUE THREAD

**Issue by sureshchouksey** [vesse/passport-ldapauth#45]
I am trying to authenticate username and password using passport-ldapauth npm. while executing the below code I am always getting error as  Bad Request. Kindly help me what is wrong with my code.
    
    var express      = require('express'),
        passport     = require('passport'),
        bodyParser   = require('body-parser'),
        LdapStrategy = require('passport-ldapauth');
    
    // Credentials from the free LDAP test server by LDAP Search
    
    var OPTS = {
      server: {
        url: 'ldap://54.227.207.201:389',
        bindDn: 'CN=simple One,CN=Users,DC=test,DC=local',
        bindCredentials: 'password',
        searchBase: 'ou=passport-ldapauth',
        searchFilter: '(uid={{username}})'
      },
      usernameField: "CN=simple One,CN=Users,DC=test,DC=local",
      passwordField: "password"
    };
    
    var app = express();
    
    passport.use(new LdapStrategy(OPTS));
    
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({extended: false}));
    app.use(passport.initialize());
    
    
    // you can refer code from here:https://github.com/vesse/passport-ldapauth
    
    app.post('/login', passport.authenticate('ldapauth', {session: false}), function(req, res) {    
    //will generate error 'Bad Request'
      res.send({status: 'ok'});
    });
    //server running at 8080
    app.listen(8080);

**Comment by vesse** [comment]
This library returns HTTP Bad Request [when username and/or password cannot be found](https://github.com/vesse/passport-ldapauth/blob/df03ccfe6542a7c9c3d9a1175fcadbd79bca5680/lib/passport-ldapauth/strategy.js#L137) from the request. This is often caused by not using default values `username` and `password` on the form and failing to provide the actual field names using [options](https://github.com/vesse/passport-ldapauth/blob/df03ccfe6542a7c9c3d9a1175fcadbd79bca5680/README.md#usage), or missing body parser. 

Also, please use Stackoverflow for these kinds of questions. This is not an issue in the library, and this forum is not help and support forum.
