### ISSUE TITLE
Errors: No way to distinguish between 'bindDN' invalid credentials error and the actual entered username and password invalid credentials error

### ISSUE THREAD

**Issue by assaf-xm** [vesse/passport-ldapauth#70]
The same error of invalid credentials ('Invalid username/password') is thrown both when the 'bindDN' credentials are wrong and when they are ok but the attempted username or password is wrong.

This makes LDAP integrations much harder.

**Comment by vesse** [comment]
So it does since underlying `ldapauth-fork` returns an error when an error occurred. Bind error is a credentials error. Developer should really know what bind credentials to use, or verify them with eg. `ldapsearch` command line tool.

You can pass a Bunyan logger to [`ldapauth-fork` ](https://github.com/vesse/node-ldapauth-fork/tree/d168cd809da170de09f206a2c81f2b0d89e38e65#ldapauth-config-options) which will produce more logs, although the traces too say `ldap authenticate: bind error:` in both cases. The trace contains the actual error too which probably shows the account used.
